"""Shared constants for the Event Management System."""

from __future__ import annotations

ROLE_ADMIN = "ADMIN"
ROLE_ORGANIZER = "ORGANIZER"
ROLE_USER = "USER"

ROLE_CHOICES = (
    (ROLE_ADMIN, "Admin"),
    (ROLE_ORGANIZER, "Organizer"),
    (ROLE_USER, "User"),
)

EVENT_STATUS_UPCOMING = "UPCOMING"
EVENT_STATUS_ONGOING = "ONGOING"
EVENT_STATUS_COMPLETED = "COMPLETED"
EVENT_STATUS_CANCELLED = "CANCELLED"

EVENT_STATUS_CHOICES = (
    (EVENT_STATUS_UPCOMING, "Upcoming"),
    (EVENT_STATUS_ONGOING, "Ongoing"),
    (EVENT_STATUS_COMPLETED, "Completed"),
    (EVENT_STATUS_CANCELLED, "Cancelled"),
)

REGISTRATION_STATUS_ACTIVE = "ACTIVE"
REGISTRATION_STATUS_CANCELLED = "CANCELLED"

REGISTRATION_STATUS_CHOICES = (
    (REGISTRATION_STATUS_ACTIVE, "Active"),
    (REGISTRATION_STATUS_CANCELLED, "Cancelled"),
)
